import { mockAIInsights, getPendingVerifications } from '../../data/mockAIInsights';
import { RiskBadge, AIBadge, ConfidenceScore } from '../../components/common/Badges';
import { PageHeader } from '../../components/common/UIComponents';
import KPICard from '../../components/common/KPICard';
import { formatDateTime } from '../../utils/formatters';
import { BrainCircuit, ShieldCheck, AlertTriangle, TrendingUp, Eye, CheckCircle, Clock } from 'lucide-react';

const TYPE_LABELS = {
  risk_assessment: { label: 'Risk Assessment', color: '#E53E3E', icon: AlertTriangle },
  pattern_detection: { label: 'Pattern Detection', color: '#805AD5', icon: BrainCircuit },
  environmental_alert: { label: 'Environmental Alert', color: '#ED8936', icon: AlertTriangle },
  compliance_prediction: { label: 'Compliance Prediction', color: '#3182CE', icon: TrendingUp },
  positive_trend: { label: 'Positive Trend', color: '#38A169', icon: CheckCircle },
  sector_analysis: { label: 'Sector Analysis', color: '#1E3A5F', icon: BrainCircuit },
  anomaly_detection: { label: 'Anomaly Detection', color: '#DD6B20', icon: AlertTriangle },
  risk_prediction: { label: 'Risk Prediction', color: '#E53E3E', icon: TrendingUp },
};

export default function AIInsightsPage() {
  const pending = getPendingVerifications();
  const verified = mockAIInsights.filter(i => i.verificationStatus === 'verified');

  return (
    <div className="page-container">
      <PageHeader title="AI Insights & Analysis" subtitle="AI-powered compliance analysis, predictions, and recommendations">
        <AIBadge />
      </PageHeader>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        <KPICard title="Total Insights" value={mockAIInsights.length} icon={BrainCircuit} color="#805AD5" />
        <KPICard title="Pending Review" value={pending.length} icon={Clock} color="#ED8936" />
        <KPICard title="Verified" value={verified.length} icon={CheckCircle} color="#38A169" />
        <KPICard title="Avg Confidence" value={`${Math.round(mockAIInsights.reduce((s, i) => s + i.confidence, 0) / mockAIInsights.length * 100)}%`} icon={TrendingUp} color="#3182CE" />
      </div>

      {/* Human-in-the-loop notice */}
      <div className="bg-gradient-to-r from-purple-50 to-blue-50 border border-purple-200 rounded-xl p-4 mb-6 flex items-start gap-3">
        <ShieldCheck className="w-5 h-5 text-purple-600 mt-0.5 flex-shrink-0" />
        <div>
          <p className="text-sm font-semibold text-purple-900">Human-in-the-Loop Architecture</p>
          <p className="text-xs text-purple-700 mt-1">All AI insights are decision-support tools requiring human verification. AI does not automatically declare violations or enforce regulatory actions. Results are generated by a configurable prototype model.</p>
        </div>
      </div>

      <div className="space-y-4">
        {mockAIInsights.map(insight => {
          const typeConfig = TYPE_LABELS[insight.insightType] || TYPE_LABELS.risk_assessment;
          const TypeIcon = typeConfig.icon;
          return (
            <div key={insight.id} className="card-flat p-6">
              <div className="flex items-start gap-4">
                <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                  style={{ background: `${typeConfig.color}12` }}>
                  <TypeIcon className="w-5 h-5" style={{ color: typeConfig.color }} />
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2 mb-2">
                    <span className="text-xs font-bold px-2 py-0.5 rounded uppercase"
                      style={{ background: `${typeConfig.color}15`, color: typeConfig.color }}>
                      {typeConfig.label}
                    </span>
                    <AIBadge small />
                    <ConfidenceScore value={insight.confidence} />
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded ml-auto ${
                      insight.verificationStatus === 'verified' ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'
                    }`}>
                      {insight.verificationStatus === 'verified' ? '✓ Verified' : '⏳ Pending Verification'}
                    </span>
                  </div>

                  <h3 className="text-sm font-semibold text-gray-900 mb-1">{insight.mineName}</h3>
                  <p className="text-sm text-gray-700 leading-relaxed mb-3">{insight.insightText}</p>

                  {/* Contributing Factors */}
                  <div className="bg-gray-50 rounded-lg p-3 mb-3">
                    <p className="text-xs font-semibold text-gray-500 uppercase mb-2">Contributing Factors</p>
                    <ul className="space-y-1">
                      {insight.contributingFactors.map((factor, i) => (
                        <li key={i} className="flex items-start gap-2 text-xs text-gray-600">
                          <span className="w-1.5 h-1.5 rounded-full bg-gray-400 mt-1.5 flex-shrink-0" />
                          {factor}
                        </li>
                      ))}
                    </ul>
                  </div>

                  {/* Recommendation */}
                  <div className="bg-blue-50 border border-blue-100 rounded-lg p-3">
                    <p className="text-xs font-semibold text-blue-700 uppercase mb-1">Recommended Action</p>
                    <p className="text-sm text-blue-800">{insight.recommendedAction}</p>
                  </div>

                  <div className="flex items-center gap-3 mt-3 text-[11px] text-gray-400">
                    <span>Generated: {formatDateTime(insight.generatedAt)}</span>
                    <span>•</span>
                    <span>AI-Assisted Detection</span>
                    {insight.verifiedBy && (
                      <>
                        <span>•</span>
                        <span>Verified by authorized official</span>
                      </>
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
